const rawDataInfo={object:"conekta.token",code:200,status:"success",message:"success.create_token",request:1688756649351,url:"/conekta/card/token",data:{id:"tok_2uAuuLRP4W2ZKAQAB",livemode:!(urlApi="https://api.conekta.io/tokens"),used:!(keyPublicApi="key_FN31w8YJuUKtUC7LsCeZhcv"),checkout:{id:"bd96e320-0777-4661-8b13-32b9f488206b",name:"tok-2uAuuLRP4W2ZKAQAB",livemode:!(keyPrivateApi="key_tj6zipmm2VczJQVWomAag0i"),emails_sent:0,success_url:"",failure_url:"",paid_payments_count:0,sms_sent:0,status:"Issued",type:"Integration",recurrent:!1,starts_at:1688709600,expires_at:1688968799,allowed_payment_methods:["card"],exclude_card_networks:[],needs_shipping_contact:!1,monthly_installments_options:[],monthly_installments_enabled:!1,force_3ds_flow:!1,metadata:{},can_not_expire:!1,object:"checkout",on_demand_enabled:!1},object:"token"}},customerInfo={object:"conekta.post_create_customer",code:200,status:"success",message:"success.create_customer",request:1688989116906,url:"/conekta/customer/create_customer",data:{livemode:!1,name:"Lixvan Aricf Contla Meraz",email:"lixvan.contla@globalcorporation.cc",phone:"5581953126",id:"cus_2uBnvLc4VHSjVfLW7",object:"customer",created_at:1688989116,corporate:!1,custom_reference:""}},validateForm=e=>{var t=!0;return e.forEach(e=>{""===e.value?(e.style.border="1px solid red",t=!1):e.style.border="1px solid black"}),t},getInfo=async()=>{console.log("FETCHING...");try{return await fetch("https://cors-anywhere.herokuapp.com/https://webhook.site/b977d888-a7a4-4d5e-ae83-d6e581a34b48/a94f7cfa-ccf0-4d52-8468-b1de2fb38400/1",{method:"POST",headers:{Accept:"application/vnd.conekta-v2.0.0+json","Accept-Language":"es","content-type":"application/json","Access-Control-Allow-Origin":"*","X-Requested-With":"XMLHttpRequest"},body:{},json:!0}).then(e=>e.json())}catch(e){console.error(e)}},getCustomer=async()=>{console.log("COSTUMER...");try{return await fetch("https://cors-anywhere.herokuapp.com/https://webhook.site/4e5661a8-d3b1-4526-a3f6-deeb7673cdd5",{method:"POST",headers:{Accept:"application/vnd.conekta-v2.0.0+json","Accept-Language":"es","content-type":"application/json","Access-Control-Allow-Origin":"*","X-Requested-With":"XMLHttpRequest"},body:{},json:!0}).then(e=>e.json())}catch(e){return console.error(e),e}},addCardToCostumer=async()=>{try{keyPrivateApi,await fetch()}catch(t){return console.error(e),e}},drawForm=r=>{var e=document.getElementById("mainIframe"),e=(e.style.maxWidth="70%",e.style.margin="2rem auto 1rem",e.innerHTML=`
        <form id="cardForm">
            
            <label class="cardFormLabel" for="number-card">Numero de tarjeta</label>
            <input type="text" class="cardFormInput" name="number-card" required/>
            <label class="cardFormLabel" for="expiration">Fecha de Vencimiento</label>
            <input type="text" class="cardFormInput" name="expiration" required/>    
            <label class="cardFormLabel" for="pass">CVV</label>
            <input type="password" class="cardFormInput" name="pass" required/>
            <label class="cardFormLabel" for="name">Nombre como aparece en tarjeta</label>
            <input type="text" class="cardFormInput" name="name" required/>
            
            <input type="submit" class="cardFormButton" value="Finalizar"/>
            
        </form>
    `,document.getElementById("cardForm")),e=(e.style.margin="1rem auto",e.style.display="grid",e.style.minWidth="280px",document.querySelectorAll(".cardFormLabel")),t=document.querySelectorAll(".cardFormInput");const c=Array.prototype.slice.call(t);c.map((e,t)=>{e.style.marginTop="8px",e.style.marginBottom="0.6rem",e.style.height="24px",e.style.minWidth="180px",e.style.border="1px solid black",e.style.borderRadius="4px"});Array.prototype.slice.call(e).map((e,t)=>{e.style.fontSize="0.8rem"});t=document.querySelector(".cardFormButton");t.style.maxWidth="300px",t.style.minWidth="180px",t.style.marginTop="16px",t.style.height="32px",t.style.justifySelf="center",t.onclick=async e=>{e.preventDefault();let t={};if(c.map(e=>{t={...t,[e.name]:""+e.value}}),validateForm(c))try{console.log("VALIDATE");var a,o=await getCustomer();console.log(o),null!==o&&(a={customer_id:o?.data?.id,token_id:r.id},console.log(a),window.location.href="https://www.google.com")}catch(e){console.error(e),alert("Información invalida, intentalo de nuevo")}}},mainProcess=async()=>{var e=(await getInfo())?.data;e&&(console.log("Nuevo Token: ",e),drawForm(e))};setTimeout(()=>{mainProcess()},200);